### ISSUE TITLE
What looks like a typo in fdisk.sh

### ISSUE THREAD

**Issue by amal-qokka** [mbrukman/stackexchange-answers#2]
Whats going on here?
https://github.com/mbrukman/stackexchange-answers/blob/ac1ef164d69c8ac7f2d78f148266b0be279b2fda/stackoverflow/24021214/fdisk.sh#L93-L104

**Comment by mbrukman** [comment]
Sorry for the delay in response. That's not a typo; those are all individual commands which are single-character, and they're on separate lines because they require <kbd>Enter</kbd> to be pressed after each one of them. The two blank lines are equivalent to pressing <kbd>Enter</kbd> twice in a row and accepting the default options that are presented.

If you want to see what this looks like interactively, just run the command manually:

```
fdisk -c -u /dev/sda
```

and see which keystrokes you input, and you should end up with the same list:

- <kbd>d</kbd> <kbd>Enter</kbd>
- <kbd>n</kbd> <kbd>Enter</kbd>
- <kbd>p</kbd> <kbd>Enter</kbd>
- <kbd>1</kbd> <kbd>Enter</kbd>
- <kbd>Enter</kbd>
- <kbd>Enter</kbd>
- <kbd>w</kbd> <kbd>Enter</kbd>

**Comment by mbrukman** [comment]
I was going to add a comment to document it in the script itself, but in fact, this is already documented in a detailed comment right above the text you quoted:

https://github.com/mbrukman/stackexchange-answers/blob/ac1ef164d69c8ac7f2d78f148266b0be279b2fda/stackoverflow/24021214/fdisk.sh#L87-L93
